### ISSUE TITLE
raidemulator needs a lot of polish

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#2161]
There's a number of issues that I think prevent the raidemulator from being more useful than it is.  It's still got a lot of benefits over the old version, but I keep running into things that make it frustrating to use.

I think a first pass of debugging is that I want to see a log and just know the the trigger text that appeared for everybody.  The list of triggers are all triggers that have matched anything (regardless of `condition`), and it is very difficult (especially now with output strings) to click on a trigger and understand what it showed.  It would be nice if instead of saying `00:01 - General Provoke | 00:01` it would say `00:01 - General Provoke | Provoke: Tini Poutini | 00:01` and say the text in the list.  Seeing the values of data are okay but only needed for extreme edge case debugging scenarios.  I can quickly add a `console.log` for debugging if needed.

In priority order, these are improvements that would make my life a lot better:
* very hard to see trigger text from analysis (mentioned above)
* trigger analysis doesn't respect delay seconds
* timeline does not play back in real time (making it really hard to evaluate against video)
* skipping ahead in the timeline does not update the list of timers properly
* timeline triggers aren't handled in analysis
* no feedback when loading files (even in the console)

**Comment by panicstevenson** [comment]
Additionally, `suppressSeconds` doesn't work as intended, and it looks as though all the `addedCombatant` lines are being parsed on log file load?
Adding a `addedCombatant` trigger with `suppressSeconds` defined will only find the first instance of the log and suppress all remaining addedCombatant logs that match.

**Comment by valarnin** [comment]
I can probably take a look at some of these at least this weekend, not sure where you'd prefer I start or if you'd want all of these as one PR or split up.

**Comment by valarnin** [comment]
> timeline does not play back in real time (making it really hard to evaluate against video)

@quisquous Can you elaborate on this? Playback should be realtime after clicking the play button.

**Comment by panicstevenson** [comment]
> @quisquous Can you elaborate on this? Playback should be realtime after clicking the play button.

I think their point is that if you skip in 10 minutes into the fight on the scrollbar at the top, you won't skip ahead in the timeline, and it will keep playing from where it was (or maybe it resets, I can't remember off the top of my head)

**Comment by quisquous** [comment]
Ah no, sorry.  I was saying that the playback was about 0.7x realtime speed.  I had a youtube video up and had to keep pausing it every second or two so that it didn't run ahead.

There's a comment to use `setInterval` because `// Use setInterval since it should account for differences in execution time automagically`.  I've had issues with `setTimeout` in the past where task scheduling delays accumulated over time, and I am not sure that I trust this comment?  (But maybe my understanding is incorrect here).  My computer is not the snappiest so it is probably a little bit more under load.  I think the correct way to do this is to recalculate the correct time inside of `tick` from the base time starting value relative to the current time and the playback speed.

**Comment by valarnin** [comment]
> I had a youtube video up and had to keep pausing it every second or two so that it didn't run ahead.

That would imply that the delay builds up over time, which would mean that your computer can't keep up with the normal emitting of lines? If that's the case, the option then becomes either:

1. Continue to use `setInterval` with its accumulation of delay
2. Switch to calculating the delay dynamically, which would lead to large 'jumps' in the timeline as it tries to catch up

`setInterval` functions by executing the next task at the specified interval or as soon as the previous task finishes, and can indeed build up a delay over time if the execution of the interval takes longer than the specified time (10ms in this case).

**Comment by valarnin** [comment]
Decided to tackle the UI responsiveness on import despite being the lowest priority, since it's the one that's going to require the most code adjustment to accommodate. Here's a WIP screenshot (progress bar isn't visually filling yet in this screenshot).

- Should I add any more info to this modal?
  - Time of encounter, zone name, status maybe?
- Maybe make it max width instead of allowing it to fill?
- Encounter load should probably use something like this as well but I'm not sure how feasible that is because of the way web workers work (they pass generic objects only, they can't pass typed objects)?

![image](https://user-images.githubusercontent.com/6119598/102372575-54c3f880-3f8d-11eb-92dc-edcf3d4a95d7.png)

**Comment by valarnin** [comment]
Here's another update on the modal look.

![image](https://user-images.githubusercontent.com/6119598/102385450-db7fd200-3f9b-11eb-9e72-0e2fc3a2eb13.png)

**Comment by valarnin** [comment]
@quisquous I think the progress modal change is ready for a PR, but there's one adjustment to non-emulator code that had to be made, as such:

```diff
diff --git a/resources/common.js b/resources/common.js
index a8b135ba..c7e13240 100644
--- a/resources/common.js
+++ b/resources/common.js
@@ -104,8 +104,8 @@ export const Util = (() => {
 })();

 (function() {
-  // Exit early if running within Node
-  if (typeof location === 'undefined')
+  // Exit early if running within Node or within a web worker
+  if (typeof location === 'undefined' || (typeof WorkerLocation !== 'undefined' && location instanceof WorkerLocation))
     return;

   const wsUrl = /[\?&]OVERLAY_WS=([^&]+)/.exec(location.href);
```

`window` doesn't exist in the scope of a `Worker`.

I feel like there should have been a better way to handle this but I couldn't figure anything out.

**Comment by panicstevenson** [comment]
Looks nice! At least in my opinion.

I think my "complaint" there was that it just didn't say anything. Although, admittedly my computer is pretty beefy so the lack of response from the browser wasn't long, so I didn't have any worries that my browser was locked up for a serious length of time. But, I could easily see that being the case.

**Comment by quisquous** [comment]
> > I had a youtube video up and had to keep pausing it every second or two so that it didn't run ahead.
> 
> That would imply that the delay builds up over time, which would mean that your computer can't keep up with the normal emitting of lines?

I think there is accumulation of scheduling delays.  I have seen this with `setTimeout`, where if you use `setTimeout` to animate something every 16ms and then decrement the time by 16ms, the scheduling delay of each task on top of the timeout accumulates over time and the real time passed and the calculated time of 16ms * number of ticks diverges over time.  I think even if the computer can keep up, delay can still accumulate, but it is worse under load when the scheduling delay is likely larger.

> If that's the case, the option then becomes either:
> 
> 1. Continue to use `setInterval` with its accumulation of delay
> 2. Switch to calculating the delay dynamically, which would lead to large 'jumps' in the timeline as it tries to catch up

3. Use `requestAnimationFrame` instead of `setTimeout` so that it's only called when the results of the update will be shown on screen, and calculate the delay dynamically.  I think this is the same as #2 roughly, but will not call `tick` unnecessarily.  If frames are dropped because `tick` is being slow, then I think that's fine.  I don't need the timeline to update at 100fps, but do need it to play back at real time roughly.

**Comment by valarnin** [comment]
Summarizing these changes as a task list for easier tracking.

- [ ] very hard to see trigger text from analysis (mentioned above)
- [ ] trigger analysis doesn't treat suppress seconds properly due to `new Date` calls in PopupText
- [ ] trigger analysis doesn't respect delay seconds
- [x] timeline does not play back in real time (making it really hard to evaluate against video) --- Fixed in PR #2235
- [x] skipping ahead in the timeline does not update the list of timers properly --- Fixed in PR #2235 due to some of the other changes
- [ ] timeline triggers aren't handled in analysis --- WIP fix in PR #2606
- [x] no feedback when loading files (even in the console) --- Fixed in PR #2230

**Comment by valarnin** [comment]
For `very hard to see trigger text from analysis (mentioned above)`, does it make sense to signify the type of output text (info/alert/alarm) via, for example, an icon or a background color or outline color for the line?

Should sound file and tts triggers be treated differently or somehow otherwise signify what the alert type is?

**Comment by valarnin** [comment]
@quisquous Here's a WIP screenshot of the changes to trigger analysis. Any feedback?
![image](https://user-images.githubusercontent.com/6119598/113238868-97c58580-9277-11eb-8d69-be32db788757.png)

**Comment by valarnin** [comment]
I'm thinking I may add another checkbox (and label both) to hide triggers that have no output but still ran (e.g. collector triggers) as well.

**Comment by valarnin** [comment]
@quisquous Now that the last issues outlined above have had fixes PR'd, I think this issue can be closed. The next thing I'll be working on is converting raidemulator to typescript. I'd prefer to do it all in one pass but I know that you've requested that large PRs like that be separated out in the past. Thoughts? Maybe we open a new issue to track moving raidemulator to TS?

**Comment by quisquous** [comment]
Thanks for all these fixes! These make the raid emulator *so* much more useful for me.  I'll close this issue now that everything is addressed.

We don't really have any other open issues for converting to typescript, mostly just because it's an ongoing project across many files.  The eventual goal is "turn everything javascript or python into typescript".  If you think there are details that need tracking, then feel free to file an issue.

And yes, please do not convert to typescript all in one pass.  The majority of typescript conversions so far have caused some bug or another, and so the more contained the patches can be the easier it is to review and catch issues at review time.

My recommendation here is:

* convert a single file at once, make minimal changes other than satisfying typescript
  * I found it easier to start bottom up in terms of dependencies, so you can use the real types of things you've already converted than make up types for them ahead of time
  * one exception to "a single file" is simple files that require minimal/no changes (maybe some of the `network_log_converter/` files fit into this category, but probably little else)
* if there's fixups that make sense to do separately, send a separate PR to do that (e.g. #2845 or #2828)
* if a file is particularly huge and complicated, consider turning off typescript errors in comments and turning them on one PR at a time (I was thinking about doing this for `popup-text.js`, for example)
